version: '3.8'

services:
  php:
    build: ./php
    container_name: yii2-php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    env_file:
      - .env

  nginx:
    image: nginx:stable
    container_name: yii2-nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: yii2-mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

volumes:
  db_data:

